### ISSUE TITLE
get_csid() fails for specific query string.

### ISSUE THREAD

**Issue by andschar** [ropensci/webchem#299] opened 2020-10-01 09:07 UTC
`get_csid()` fails with following query string. @stitam you mentioned you would provide a ChemSpider update somewhere (?) - can't find it anymore. Can you check on this too?

```r
query = '[2R-[2R*(4R*,8R*)]]-3,4-Dihydro-2,7,8-trimethyl-2-(4,8,12-trimethyltridecyl)-2H-1-benzopyran-6-ol'
get_csid(query = query, apikey = apikey)
```

**Comment by stitam** [comment] 2020-10-07 07:44
Thanks @andschar for raising this issue. I'll look into it and include a fix in PR #302. It currently returns `NA` with HTTP 400 (bad request). I searched for the substance at chemspider.com, and found zero results. What outcome do you expect? `NA` but with HTTP 404 (not found)?

**Comment by stitam** [comment] 2020-10-07 12:40
The query is probably failing because of `*`. Can you provide an example with `*` that also returns a result at chemspider.com?

**Comment by andschar** [comment] 2020-10-07 13:00
You are right, this error is caused by the `*` and I can't produce a correct result. I would however catch that error, so that such a query doesn't stop the function. If I remember correctly, I queried some thousand compound names when I raised this issue and it's bad if such an erroneous string breaks the whole process at say string number 650.

**Comment by stitam** [comment] 2020-10-08 07:06
That must have been frustrating. So the problem is that the function breaks when the query is invalid. I think this is sovled in the PR, when the query is invalid, `get_csid()` still returns a `tibble`.

**Comment by andschar** [comment] 2020-10-08 15:17
Alright, once #302 is merged, we can close this!

**Comment by stitam** [comment] 2020-10-26 21:02
Hi @andschar PR #302 is now merged. I tested your compound, it no longer returns an error, it returns `NA`.

**Closed by stitam** 2020-10-26 21:02 UTC
Labels: bug
