### ISSUE TITLE
get_cid cannot handle #

### ISSUE THREAD

**Issue by stephanflemming** [ropensci/webchem#276] opened 2020-08-16 22:10 UTC
Hi,

I try to fetch the pubchem cid of the following smiles `N#CC4=C(N1CCCNCC1)N(CC=C(Cl)Cl)C5C(=O)N(Cc3nccc2ccccc23)C=NC4=5` (Pubchem entry https://pubchem.ncbi.nlm.nih.gov/compound/23633624) via 

```
get_cid("N#CC4=C(N1CCCNCC1)N(CC=C(Cl)Cl)C5C(=O)N(Cc3nccc2ccccc23)C=NC4=5", from = "smiles")
```

and run into the following error

```
Querying N#CC4=C(N1CCCNCC1)N(CC=C(Cl)Cl)C5C(=O)N(Cc3nccc2ccccc23)C=NC4=5. OK (HTTP 200).
Error: lexical error: invalid char in json text.
                                       <?xml version="1.0"?> <PC-Compo
                     (right here) ------^
```

Probably it's the `#` that causes this error.

Thanks,
Stephan

**Comment by Aariq** [comment] 2020-08-17 12:57
Hi Stephan,

You're absolutely correct that `#` was the problem.  We fixed this in the development version of webchem, so you can either install it with `remotes::install_github("ropensci/webchem")` or pass your SMILES query through `URLencode()`.

-Eric

Note: This is a duplicate of #269

**Closed** 2020-08-17 12:58 UTC
