### ISSUE TITLE
Option to search substances in PubChem

### ISSUE THREAD

**Issue by stanstrup** [ropensci/webchem#216] opened 2020-02-25 15:34 UTC
Could we have an option in `get_cid` to also search through substances?

For example the CAS number "152957-32-9" is listed as a synonym for SID 349678457 but not in the CID entry. Yet the SID can point me to the CID.
So the following URL would give me what I was after:
https://pubchem.ncbi.nlm.nih.gov/rest/pug/substance/name/152957-32-9/cids/JSON

So I suggested an option that if TRUE would also search "substance". You might get duplicate CIDs returned from compounds and substance and those should be de-duplicated with `unique`.

**Comment by Aariq** [comment] 2020-02-25 19:03
Sounds good to me.  I assume not all SIDs have corresponding CIDs though, right?  So even when `search_substances = TRUE` (or whatever), and there is a SID, it would return `NA` if there's no CID.  If we ever wanted a `get_sid` function, that should be implemented separately I think.

**Comment by stanstrup** [comment] 2020-03-02 15:36
I accidentally pushed directly to this repo. I didn't even know I had write access. Should the commit be rolled back? 417d1c81d01ca9f5417e66aa7e41ec1d81642ecc

**Comment by Aariq** [comment] 2020-03-10 22:45
If you can roll it back and submit as a pull request that would be best I think—partly because I have some suggestions and they are easier to make in PRs

**Comment by stitam** [comment] 2020-04-04 15:09
Hi, I also think it would be better to separate this functionality into `get_sid()`. Apart from compounds and substances, PubChem also has assays, genes, and patents. Maybe it would be better to deprecate `get_cid()` and use something like `get_pcid()` to query all sorts of PubChem ids?

**Comment by stitam** [comment] 2020-04-16 10:37
I started working on a highly customizable function that can assemble and execute all sorts of PubChem PUG-REST queries. The PR would revert `get_cid()` to its original functionality and introduce this new function. Would this be an acceptable solution for now?

**Comment by Aariq** [comment] 2020-05-04 19:09
I do like the idea of having the option to search substances like in the original suggestion.  It's definitely not the same as having a separate function to get SIDs. The problem is that there are some chemicals, with CIDs that are not listed as compounds but rather as substances in pubchem.  (i.e. they are at a https://pubchem.ncbi.nlm.nih.gov/substance/ URL). 

``` r
library(webchem)

# I want a CID for Cortisol 21-Sulfate Potassium Salt

get_cid("Cortisol 21-Sulfate Potassium Salt")
#> https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/cids/JSON
#> Warning in foo(query = .x, from = from, match = match, verbose = verbose, : No
#> CID found that matches the given name. Returning NA.
#> # A tibble: 1 x 2
#>   query                              cid  
#> * <chr>                              <lgl>
#> 1 Cortisol 21-Sulfate Potassium Salt NA

# No CID?  That's not true though!

get_cid("Cortisol 21-Sulfate Potassium Salt", search_substances = TRUE)
#> https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/cids/JSON
#> Warning in foo(query = .x, from = from, match = match, verbose = verbose, : No
#> CID found that matches the given name. Returning NA.
#> https://pubchem.ncbi.nlm.nih.gov/rest/pug/substance/name/cids/JSON
#> More then one Link found for ''.
#> Returning all matches.
#> # A tibble: 3 x 2
#>   query                              cid      
#> * <chr>                              <chr>    
#> 1 Cortisol 21-Sulfate Potassium Salt <NA>     
#> 2 Cortisol 21-Sulfate Potassium Salt 129011998
#> 3 Cortisol 21-Sulfate Potassium Salt 131874189

# It does have a CID associated with it.
```

<sup>Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by stitam** [comment] 2020-05-05 10:40
My main concern is that  the `get_cid()` function would return either CIDs or SIDs, which is inconsistent with the name of the function and might be confusing.  On the other hand, we would get away with one less exported functions. Is this the reason you suggest the `search_substances` argument instead of a separate `get_sid()` function? I am ok with this, we will need more complex function documentation and `match.arg()` conditions because the two domains accept different input types, but this is manageable. One small thing, I would rather call the argument `domain` with values `"compound"` and `"substance"` so if we later decide we want this function to handle AIDs as well, it will be much simpler. Let's reach consensus and I will implement it in PR #239.

**Comment by Aariq** [comment] 2020-05-05 13:38
I think you misunderstand.  131874189 is the CID for the substance, not the SID.

**Comment by stitam** [comment] 2020-05-05 17:10
Oh yes, I definitely misunderstood, thanks @Aariq! In this case there is no function name inconsitency, which is great. However, as CIDs can be acquired through queries from all three domains (compound, substance, assay), naming the new argument `domain` instead of `search_substances` still has benefits. Also whatever I wrote about documentation and `match.arg()` is still valid I think, e.g. `get_cid()` will not work when you search a formula in the substance domain.

**Comment by Aariq** [comment] 2020-05-05 18:34
What I like about `search_substances` is that it searches both the compound **and** substance domains and then collapses the results by removing duplicate CIDs.  So, what would be cool is a similar behavior with something like `domain = c("compound", "substance")`.

**Comment by stitam** [comment] 2020-05-06 08:15
Then why not always search all valid domains for the given query type and collapse the results? This way we wouldn't need any new arguments. Is there any situation in which this woud be undesirable?

**Comment by Aariq** [comment] 2020-05-06 20:44
> Then why not always search all valid domains for the given query type and collapse the results? This way we wouldn't need any new arguments. Is there any situation in which this woud be undesirable?

It's slower.  For a lot of compounds, it may be noticeably slower.

**Comment by stitam** [comment] 2020-05-07 09:49
So the problem I'd like to solve is to update `get_cid()` so that CIDs can be retrieved through queries from all three domains. There are two query types that are present in more than one domain: `"name"` can be queried from all three domains, `"sourceall/<source name>"` can be queried from the substance and assay domains.

I feel there has to be a compromise if we want to keep the arguments simple: 1. we keep `search_substances` but then `get_cid()` won't be able to search the assay domain for cids. 2. we introduce the `domain` argument instead, but then 2/a we either won't be able to search multiple domains in the same query (btw this will return the same output as a query on the website) or 2/b we will always search multiple domains when the query type is `"name"` or `"sourceall/<source name>"` (which may be slow and/or confusing).

I also like collapsing, but if there has to be a compromise, I would prefer `domain` without collapsing, because of the ability to search all three domains.

**Comment by Aariq** [comment] 2020-05-13 20:25
How about this:

`get_cid("hexanol", from = "name", domain = c("compound", "substance", "assay")` would return a tibble with one row while `get_cid("CCCC", from = "smiles", domain = c("compound", "substance")` would error with `Error, can only search 'compound' domain for query type 'smiles'`

**Comment by stitam** [comment] 2020-05-14 11:55
Thanks @Aariq, I thought about your suggestion, but I couldn't find a simple way to implement it so far. I pushed my edits to PR #239. The function currently queries only one domain, but the user can call `get_cid()` on various domains and merge the tibbles easily. I suggest we merge this so we can solve issues #206 and #216 and come back to it later if this becomes a priority. What do you think?

**Comment by stitam** [comment] 2020-05-15 09:14
I think `get_cid("152957-32-9")` didn't find the right CID because the query url was querying a name and not a cas. This query works fine: https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/xref/rn/152957-32-9/cids/JSON.

This is how the updated `get_cid()` function queries from CAS numbers:

```
# queries the compound domain by default, rn stands for CAS RN
# https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/xref/rn/152957-32-9/cids/JSON
get_cid("152957-32-9", from = "xref/rn")

# queries the substance domain
# https://pubchem.ncbi.nlm.nih.gov/rest/pug/substance/xref/rn/152957-32-9/cids/JSON
get_cid("152957-32-9", from = "xref/rn", domain = "substance")
```

The two functions return identical results. I will close this issue for now, let's open it again, if we decide we need the functionality to query multiple domains in one request.

**Closed by stitam** 2020-05-15 09:14 UTC
Labels: enhancement, question
