### ISSUE TITLE
service not available

### ISSUE THREAD

**Issue by QizhiSu** [ropensci/webchem#331] opened 2021-11-08 07:57 UTC
Hi,
I am experiencing "service not available" issue with the get_cid() function recently. Does anyone have the same problem? I am not sure what is the problem because Pubchem can be assessed from the website. 

Best,
Qizhi Su

**Comment by stitam** [comment] 2021-11-08 09:51
Hi @QizhiSu, thanks for raising this issue, I can confirm the function fails on my end as well. It was working last week, so probably the API is temporarily down. I suggest we wait and see for now.

**Comment by cujoisa** [comment] 2021-11-08 15:35
Hi, 
Just wanted to chime in and say I also am experiencing the same issue.

Chinmaya

**Comment by stitam** [comment] 2021-11-09 21:22
Hi, thanks for flagging it, I think I am one step closer to finding the cause of the issue. For those who are interested in looking at the code: `ping_service("pc")` returns `FALSE` which causes most pubchem functions to return an error. However, the service is not down, if I comment out this line, the functions work. Will push a fix asap.

**Comment by stitam** [comment] 2021-11-09 21:47
PR #332 addresses this issue, can you confirm it works on your end as well?

**Comment by QizhiSu** [comment] 2021-11-09 22:11
I am not sure if I understand you correctly. 
ping_service("pc") returns FALSE on my side as well.

**Comment by schymane** [comment] 2021-11-09 22:15
I just tried a fresh install from github and still get the errors ... it's failed on every example I tried this evening, even from your docs. I know my system is somewhat out of date but something very similar worked fine a few days ago .. 

```
> selected_properties <- c("Title","ExactMass","MolecularFormula","XlogP",
+                          "InChI","IsomericSMILES","InChIKey","IUPACName")
> # retrieve info with webchem
> CID_info_all <- as.data.table(webchem::pc_prop(unique_parent_cids, selected_properties))
 Service not available. Returning NA.
Error in webchem::pc_prop(unique_parent_cids, selected_properties) : 
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.2.1    usethis_1.5.1     data.table_1.12.8 webchem_1.1.1  
```

**Comment by stitam** [comment] 2021-11-10 07:45
After merging PR #332 `get_cid()` was fixed on my computer. I tried a clean install of the dev version as well, i.e., I manually deleted the installed webchem library and installed it again with `install_github("ropensci/webchem")`. Again, the function works well. I tried other pubchem examples as well, `pc_prop()`, `pc_sect()`, `pc_synonym()` all seem to work. This is strange, @schymane did you do the fresh install similarly to my approach?

**Comment by QizhiSu** [comment] 2021-11-10 07:55
I immediately test your approach and it works again! @stitam

**Comment by schymane** [comment] 2021-11-10 10:54
It seems it was a dependency issue my side most likely ... first Bego tried this morning (she has a much newer version of R than me) with the code I sent her last night and it worked for her straight off once upgrading: 

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.0 webchem_1.1.1    

loaded via a namespace (and not attached):
 [1] xml2_1.3.2       magrittr_2.0.1   tidyselect_1.1.1 rvest_1.0.2      R6_2.5.1         rlang_0.4.11     fansi_0.5.0      stringr_1.4.0    httr_1.4.2       dplyr_1.0.7      tools_4.1.0      utf8_1.2.1      
[13] DBI_1.1.1        ellipsis_0.3.2   assertthat_0.2.1 tibble_3.1.6     lifecycle_1.0.1  crayon_1.4.2     purrr_0.3.4      vctrs_0.3.8      curl_4.3.2       glue_1.5.0       stringi_1.7.5    compiler_4.1.0  
[25] pillar_1.6.4     generics_0.1.1   data.tree_1.0.0  jsonlite_1.7.2   pkgconfig_2.0.3 

```

Then I had to fight package upgrades for ages on a different laptop than last night ... but eventually got there and can now confirm it works for me too installing from GitHub. Will have to try on the other machine at a later point...

```
> selected_properties <- c("Title","ExactMass","MolecularFormula","XlogP",
+                          "InChI","IsomericSMILES","InChIKey","IUPACName")
> # retrieve info with webchem
> CID_info_all <- as.data.table(webchem::pc_prop(unique_parent_cids, selected_properties))
```

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.6 devtools_2.4.2    usethis_2.1.3    

loaded via a namespace (and not attached):
 [1] compiler_3.6.1    pillar_1.6.4      prettyunits_1.0.2 remotes_2.4.1     tools_3.6.1      
 [6] testthat_3.1.0    pkgbuild_1.2.0    pkgload_1.2.3     jsonlite_1.7.2    memoise_2.0.0    
[11] lifecycle_1.0.1   tibble_3.1.6      pkgconfig_2.0.3   rlang_0.4.12      cli_3.1.0        
[16] rstudioapi_0.13   curl_4.3.2        yaml_2.2.1        fastmap_1.0.1     stringr_1.4.0    
[21] xml2_1.3.2        httr_1.4.2        withr_2.4.2       dplyr_1.0.7       desc_1.4.0       
[26] generics_0.1.1    fs_1.5.0          vctrs_0.3.8       tidyselect_1.1.1  rprojroot_1.3-2  
[31] data.tree_1.0.0   glue_1.5.0        R6_2.5.1          processx_3.5.2    fansi_0.5.0      
[36] webchem_1.1.1     sessioninfo_1.1.1 callr_3.7.0       purrr_0.3.4       magrittr_2.0.1   
[41] backports_1.1.5   ps_1.6.0          ellipsis_0.3.2    rvest_1.0.2       assertthat_0.2.1 
[46] utf8_1.2.2        stringi_1.7.5     cachem_1.0.6      crayon_1.4.2     


```


If you could bump the version number that would be great, because both old and new versions had the same version number and I could not easily tell if I had the changes correctly or not ...

**Comment by stitam** [comment] 2021-11-10 13:57
Sure, thanks @schymane for flagging this. I'll close the issue now.

**Closed by stitam** 2021-11-10 13:57 UTC
