### ISSUE TITLE
Fix tests that are currently skipped

### ISSUE THREAD

**Issue by stitam** [ropensci/webchem#255] opened 2020-05-11 15:00 UTC
Some of the tests are either skipped or commented out because they fail. Such tests can be found in:

* [ ] test-chemid.R
* [ ] test-chemspider.R
* [ ] test-cts.R

**Comment by Aariq** [comment] 2020-05-15 15:52
I'm working on #224 and a couple of these are getting fixed incidentally.

**Comment by stitam** [comment] 2020-05-17 13:51
PR #243 is giving me a lot of headache. Whenever I trigger the Appveyor/Travis tests, at least one of the tests on one of the platforms fail, and this seems to be random. Out of curiosity, I checked a skipped `cts` test as well. The server is up, and the request sometimes works, sometimes not. I think this is what's causing the test failures. Maybe ping_service() is not an ideal solution and each test should be skipped based on their own HTTP status code? In this case, each function call would have to return e.g. a vector of status codes for the vector of queries. I think this could be done with `attributes`, but it would require quite some rework on most functions. What do you think?

**Comment by Aariq** [comment] 2020-05-17 14:22
CTS seems inconsistent right now.  I tried pasting the `qurl` into my browser:
http://cts.fiehnlab.ucdavis.edu/service/compound/XEFQLINVKFYRCS-UHFFFAOYSA-N.  The first time, I got an error (code 500 I think?), but subsequent times it seems to work. Maybe instead of directly converting the URL with `fromJSON(qurl)` we can use `RETRY("GET", qurl)`?

**Comment by Aariq** [comment] 2020-05-17 14:26
As for the Appveyor one that consistently produces the following error:
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed).
```

I have a suspicion this has something to do with the versions of Windows and libcurl that Appveyor uses, and I'd be satisfied with `skip_on_appveyor()` for now.  I spent about 30 min trying to google this error and didn't come up with anything that looked remotely like an easy fix.

**Comment by stitam** [comment] 2020-05-17 14:51
I see the same responses here.

I never used `httr::RETRY()` before, but it looks promising!

> I'd be satisfied with skip_on_appveyor() for now. 

Do you mean skipping _all_ tests on AppVeyor?

I'll do these edits, I am super incentivised to get  PR #243 out of the way:D

**Comment by stitam** [comment] 2020-05-17 15:31
One problem with `RETRY` it calls `stop()` if it cannot get a successful response so I think the edits have to be made togather with fixing invalid inputs.

**Comment by Aariq** [comment] 2020-05-17 18:38
> > I'd be satisfied with skip_on_appveyor() for now.
> 
> Do you mean skipping _all_ tests on AppVeyor?

No, just the `cir_` one, which seems to be the one that's failing?  

>`RETRY` calls `stop()` if it cannot get a successful response so I think the edits have to be made together with fixing invalid inputs. 

I'm not sure I understand what you mean.  It seems like it works just like `GET`, except it only errors if it gets an error twice in a row.  It can still be wrapped in `try()`

**Comment by stitam** [comment] 2020-05-17 18:51
In PR #243 AppVeyor/Travic failed because of cts, nist, pubchem, and wikidata tests. I am not sure which failed when, it all seemed quite random. `RETRY()`: I just noted that the solution is more complex that wrapping each `GET()` and `POST()` call into `RETRY()`. It has to be wrapped in `try()` as well, and try errors have to be resolved appropriately so that functions remain vectorised.

**Comment by Aariq** [comment] 2020-05-18 22:36
How about this for `cts_convert()` : 

```r
    Sys.sleep( rgamma(1, shape = 15, scale = 1/10))
    res <- RETRY("GET", qurl)
   if(http_error(res)) {
      warn_for_status(res, paste("query", query, ". Returning NA"))
      return(NA)
    } else {
      out <- fromJSON(res)
    }
    if (length(out$result[[1]]) == 0) {
        message("Not found. Returning NA.")
        return(NA)
    }
```

**Comment by Aariq** [comment] 2020-05-19 01:22
`cts_convert()` fails on conversion to "Chemical Name" due to a bug in the service reported here: https://bitbucket.org/fiehnlab/ctsproxy/issues/23/chemical-name-conversion-is-not-working

Won't be able to fix this test!

**Comment by Aariq** [comment] 2020-05-19 01:48
> `RETRY` calls `stop()` if it cannot get a successful response so I think the edits have to be made together with fixing invalid inputs.

what about something like this for `cts_compinfo()`?  It'll try a second time and hopefully not get the http 500 error on appveyor, and it seems to be working fine (not calling `stop()`).  The problem is that the CTS service doesn't return a different error for "I'm broken" and "query not found", so if you search something that doesn't exist, then it takes like 3 times as long to return `NA`.  Not worth it just to fix a sporadic Appveyor fail, IMO, but maybe useful code for other functions.

```r
Sys.sleep(rgamma(1, shape = 15, scale = 1/10))
    res <- RETRY("GET", qurl)
    if(http_error(res)) {
      warn_for_status(res, task = paste("querying", query, ". Returning NA"))
    } else {
      out <- try(fromJSON(content(res, as = "text")))
      #could be shortened to content(res), but output format is slightly different
    }
    if (inherits(out, "try-error")) { #no longer necessary?
      warning('Not found... Returning NA.')
      return(NA)
    }
```

Also, reading the help file for `warn_for_status()` makes me think we should be using this for everything rather than `try(GET())`

**Closed** 2020-07-08 21:38 UTC
Labels: bug
